---
- name: Configure screen recording
  hosts: node1
  gather_facts: false

  tasks:
    - name: Install the package
      package:
        name: "{{ package_name }}"
        state: present
      tags:
        - install_package

    - name: Debug package_name variable
      debug:
        var: package_name
      tags:
        - debug_variable
